# Generated by Django 3.1.7 on 2021-05-03 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slices_App', '0002_auto_20210411_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='slices_model',
            name='clicks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
