# Generated by Django 3.1.7 on 2021-03-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Slices_App', '0003_auto_20210329_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_Image', models.URLField(max_length=400)),
                ('display_Name', models.CharField(max_length=40)),
                ('sub_Name', models.CharField(max_length=20)),
                ('link_url', models.URLField(max_length=400)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
                ('my_Slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slices_App.slices_model')),
            ],
        ),
    ]
