# Generated by Django 3.1.7 on 2021-04-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Slices_App', '0001_initial'),
        ('Links_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_model',
            name='my_Slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slices_App.slices_model'),
        ),
    ]
