# Generated by Django 3.1.7 on 2021-03-29 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slices_App', '0002_auto_20210328_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slices_model',
            name='slice_Name',
            field=models.CharField(error_messages={'unique': 'This slice name all ready exist'}, help_text='Only Numbers, Lowecase-Letter and UserScore ( _ ) is allowed', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-z_]+$', message='Enter a valid Slice Name. Only Numbers, Lowecase-Letter and UserScore ( _ ) is allowed')]),
        ),
    ]
