# Generated by Django 3.1.7 on 2021-05-18 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slices_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_Name', models.CharField(error_messages={'unique': 'This slice name all ready exist'}, help_text='Only Numbers, Lowecase-Letter and UserScore ( _ ) is allowed', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-z_]+$', message='Enter a valid Slice Name. Only Numbers, Lowecase-Letter and UserScore ( _ ) is allowed')])),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
                ('clicks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
