# Generated by Django 3.1.7 on 2021-05-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Slices_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slices_model',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='slices_model',
            unique_together={('author', 'slice_Name')},
        ),
    ]
