# Generated by Django 3.1.7 on 2021-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfile_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile_model',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
