# Generated by Django 3.1.7 on 2021-05-03 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfile_App', '0003_auto_20210503_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile_model',
            name='clicks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
