# Generated by Django 3.1.7 on 2021-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfile_App', '0004_auto_20210503_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile_model',
            name='contact_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
