# Generated by Django 3.1.7 on 2021-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfile_App', '0005_usersprofile_model_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile_model',
            name='contact_Email',
            field=models.EmailField(blank=True, help_text='Public email, visible to all', max_length=254, null=True),
        ),
    ]
