# Generated by Django 3.1.7 on 2021-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_Image', models.URLField(blank=True, max_length=400, null=True)),
                ('display_Name', models.CharField(max_length=40)),
                ('sub_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('link_url', models.URLField(max_length=400)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
            ],
        ),
    ]
